deploy:
  provider: releases
  file: jverification-hbuilder-plugin/nativeplugins/JG-JVerification
  skip_cleanup: true
  on:
    #tags: true
    push:
      branches: [ jg ]
  file: *.tar.gz
  file_glob: true
