name: Release

on:
  push:
    branches:
      - jg # 在 master 分支发生更新时执行此 action

jobs: 
  draft_release:
    strategy:
      matrix:
        go_version: [1.13]
        os: [ubuntu-latest]
    
    name: release
    runs-on: ubuntu-latest
    steps:
      
      - name: Gzip
        
        run: |
          pwd
          ls -al
          mkdir jver-${{ matrix.go_version }}
          cp ./test.js jver-${{ matrix.go_version }}
          tar -czvf jver-${{ matrix.go_version }}.tar.gz jver-${{ matrix.go_version }}
          

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          name: jverification-hbuilder-plugin/nativeplugins/JG-JVerification
          args: jver-${{ matrix.os }}.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
