name: Release

on:
  push:
    branches:
      - jg # 在 master 分支发生更新时执行此 action

jobs: 
  draft_release:
    strategy:
      matrix:
        version: [1.13]
        os: [ubuntu-latest]
    
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.version }}
        uses: actions/setup-go@v1
        with:
          version: ${{ matrix.version }}
        id: go

      - name: Checkout
        uses: sherryQwl/jverification-hbuilder-plugin@jg

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
          
      
      - name: Gzip
        run: |
          pwd
          ls -al ../
          mkdir jver-${{ matrix.version }}
          cp ./test.js jver-${{ matrix.version }}
          tar -czvf jver-${{ matrix.version }}.tar.gz jver-${{ matrix.version }}
          

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          name: jverification-hbuilder-plugin/nativeplugins/JG-JVerification
          args: jver-${{ matrix.os }}.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
