name: Release

on:
  push:
    branches:
      - jg # 在 master 分支发生更新时执行此 action

jobs: 
  release:
    if: github.repository == 'sherryQwl/jverification-hbuilder-plugin'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [1.13]
        os: [ubuntu-latest]
    
    name: release
    #runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Gzip
        run: |
          pwd
          ls -al 
          mkdir jver-${{ matrix.version }}
          cp -r nativeplugins/JG-JVerification jver-${{ matrix.version }}
          tar -czvf jver-${{ matrix.version }}.tar.gz jver-${{ matrix.version }}
          

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: jver-${{ matrix.version }}.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
